platform :ios, '11.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'git@gitlab.3squared.com:iOSLibraries/CocoaPodSpecs.git'

target 'PeakNetworkExamples' do
  use_frameworks!

  pod 'PeakNetwork', :path => '../'
end
